version: '3.7'

services:
  db:
    image: microsoft/mssql-server-windows-express:2016
    restart: always
    environment:
      - sa_password=Sql!Expre55
      - ACCEPT_EULA=Y
  blazor:
    build:
      context: .
      dockerfile: Dockerfile.windows
    depends_on:
      - db
    ports:
      - "8888:80"
    #restart: always
    environment:
      - DBHOST=db
      - DBNAME=sql-docker
      - DBPORT=1433
      - DBUSERNAME=sa
      - DBPASSWORD=Sql!Expre55
      - ASPNETCORE_ENVIRONMENT=Development
   

   
    